// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DbFirstSample.Models
{
    public partial class MovieActor
    {
        public int ActorId { get; set; }
        public int MovieId { get; set; }

        public virtual Movie Actor { get; set; }
        public virtual Actor Movie { get; set; }
    }
}